### PR TITLE
pipeline: also test metal4k installs

### PR DESCRIPTION
**Pull request by jlebon**
`kola testiso` knows how to do this now!

https://github.com/coreos/coreos-assembler/pull/1312

### CODE REVIEW

**Comment by jlebon** [comment]
Rebased this now! Though not tested in a developer pipeline.

**Comment by jlebon** [comment]
Actually, we should use https://github.com/coreos/coreos-assembler/pull/1358 first before merging this so we avoid recompressing a bunch of times.

**Comment by jlebon** [comment]
OK, updated this to use `cosa compress --artifact metal --artifact metal4k`!

**Comment by dustymabe** [comment]
still LGTM

**Pull request merged**
