### PR TITLE
plugins: add jms-messaging

### PR DESCRIPTION
**Pull request by jlebon**
This plugin will allow us to interact with fedmsgs in various ways more easily (notably triggering jobs on messages and sending messages).

### CODE REVIEW

**Comment by jlebon** [comment]
Still need to test this works in stage.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by jlebon** [comment]
OK, I've tested this plugin in stage now and it's working well! Rebased and marked ready for final review.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
