### PR TITLE
pipeline: start building installer ISOs

### PR DESCRIPTION
**Pull request by jlebon**
Start using the new `buildextend-installer` command from:
https://github.com/coreos/coreos-assembler/pull/306

### CODE REVIEW

**Comment by jlebon** [comment]
(Haven't tried this out locally myself yet.)

**Comment by dustymabe** [comment]
hold - we've got some more prereqs that haven't landed yet

**Comment by jlebon** [comment]
You mean https://github.com/coreos/fedora-coreos-config/pull/47, right?

**Comment by dustymabe** [comment]
There's actually a few things:

- https://github.com/coreos/fedora-coreos-config/pull/47
- https://github.com/coreos/ignition-dracut/pull/43
- Need an rpm for https://github.com/coreos/coreos-installer

**Comment by dustymabe** [comment]
everything merged! - will merge this on monday so I can monitor the pipeline when I do

**Comment by dustymabe** [comment]
can finally merge. this :)

**Pull request merged**
