### PR TITLE
pipeline: switch default branch to testing-devel

### PR DESCRIPTION
**Pull request by jlebon**
This will shortly be the default branch in the repo.

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm actually, maybe it's cleaner to just make it blank, and handle that in the Groovy code so `git clone` does the right thing.

**Comment by dustymabe** [comment]
LGTM

Maybe we should leave a master branch with a single file README.md that explains the setup of the repo.

**Comment by dustymabe** [comment]
> Maybe we should leave a master branch with a single file README.md that explains the setup of the repo.

that is for the fedora-coreos-config repo

**Comment by jlebon** [comment]
> Hmm actually, maybe it's cleaner to just make it blank, and handle that in the Groovy code so git clone does the right thing.

Hmm nevermind, seems like BuildConfigs default to `master` rather the real default branch. So let's roll with what we have here!

> Maybe we should leave a master branch with a single file README.md that explains the setup of the repo.

Hmm, kinda like in the RHEL dist-git? Wouldn't having a `master` branch at all send mixed signals though? Seems clearer to just not have it at all so anything trying to clone/checkout `master` just fails. But yeah, definitely we should explain the setup in the `README.md` on the default branch.

**Comment by dustymabe** [comment]
> Hmm, kinda like in the RHEL dist-git? Wouldn't having a `master` branch at all send mixed signals though? Seems clearer to just not have it at all so anything trying to clone/checkout `master` just fails. But yeah, definitely we should explain the setup in the `README.md` on the default branch.

ok - i'm cool either way

**Comment by jlebon** [comment]
> But yeah, definitely we should explain the setup in the README.md on the default branch.

https://github.com/coreos/fedora-coreos-config/pull/102

**Pull request merged**
