### PR TITLE
Prep patches for prep patches for CoreOS CI

### PR DESCRIPTION
**Pull request by jlebon**
Split out of #197.

### CODE REVIEW

**Comment by jlebon** [comment]
Heh, wanted to use `deploy --dry-run` in CI, but of course, the master doesn't have py3. We can do that in a container, but we'll need to install `oc` too. Anyway, I can do that in a follow-up!

**Comment by jlebon** [comment]
Releases built, merging!

**Comment by dustymabe** [comment]
> Releases built, merging!

but we still haven't run the release pipeline for them? currently waiting on the releing ostree import

**Comment by jlebon** [comment]
> but we still haven't run the release pipeline for them? currently waiting on the releing ostree import

Fair, though the risk should be pretty minimal (and if somehow it does break the release job, I'll be on standby to make sure we get it fixed :)  ).

**Pull request merged**
