### PR TITLE
Bump Jenkins to v2.176.3

### PR DESCRIPTION
**Pull request by jlebon**
Not tested yet.

### CODE REVIEW

**Comment by dustymabe** [comment]
I can test that this at least comes up in communishift once you feel good about the change in CCI.

**Comment by jlebon** [comment]
Tested working!

**Comment by jlebon** [comment]
Rolled out! :heavy_check_mark: 

(I had to `oc edit dc jenkins` and do `s/:latest/:2/` due to https://github.com/coreos/fedora-coreos-pipeline/pull/70. On that topic, I think we should periodically nuke everything and re-provision to make sure we don't fool ourselves into thinking we're GitOps'ing when really we're relying on hysteresis from e.g. 14 months ago. I think that's the idea with https://github.com/openshift/release too.)

**Comment by dustymabe** [comment]
> I think we should periodically nuke everything and re-provision to make sure we don't fool ourselves into thinking we're GitOps'ing when really we're relying on hysteresis from e.g. 14 months ago

+1. Maybe once a month (or every 4 weeks would be cleaner). The only concern i have here is:

- I'd love to just delete/re-create project to ensure we clean up everything, but that's not easy in an environment we don't own
- PVCs are hard because I think they have to manually recycle them in CCI and we won't be guaranteed to get a new volume

**Pull request merged**
