### PR TITLE
jenkins/plugins: update to latest versions

### PR DESCRIPTION
**Pull request by coreosbot-releng**

### CODE REVIEW

**Comment by aaradhak** [comment]
The update of three plugins seem to be having issues from the update list, the below plugin versions seem to run into the dependency issues :

```
generic-webhook-trigger:2.2.2,
github-oauth:611.v70d151e60ec4 ,
slack:741.v00f9591c586d

```

Updated the Jenkins plugins to specific versions to resolve dependency issues. Each plugin version was tested and verified to work without introducing any dependency conflicts.

**Comment by aaradhak** [comment]
I will squash and merge the commits once it is reviewed.

**Review by jlebon — APPROVED** [review]
Looks sane to me, thanks!

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
