### PR TITLE
config: Start producing kubevirt artifact for x86_64

### PR DESCRIPTION
**Pull request by gursewak1997**
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1126#issuecomment-1452628138

### CODE REVIEW

**Comment by dustymabe** [comment]
LGTM - but let's hold this until after the triple release going out later this week.

**Comment by dustymabe** [comment]
Also, let's get the `stream-metadata-{go,rust}` library updates that we found were needed in place before we merge this.

**Comment by gursewak1997** [comment]
> Also, let's get the `stream-metadata-{go,rust}` library updates that we found were needed in place before we merge this.

Those are already merged in:
- https://github.com/coreos/stream-metadata-rust/pull/39
- https://github.com/coreos/stream-metadata-go/pull/57

**Comment by dustymabe** [comment]
oh nice!

**Comment by dustymabe** [comment]
Though I do wonder if we also need a release to happen in those projects or not cc @jlebon 

Either way this LGTM.

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
Yes, stream-metadata-go at least needs to be tagged for Dependabot to bump it in cosa. I'm not sure where stream-metadata-rust is used (I thought in coreos-installer, but that's not the case). Though it looks like the PRs are just changing test fixtures. Since the schema itself hasn't changed, we don't need to get releases out or block this PR.

**Pull request merged**
