### PR TITLE
utils: update URLs in protected jenkins list

### PR DESCRIPTION
**Pull request by marmijo**
Add the new prod jenkins URL and update the namespace of the devel jenkins in the ITUP cluster. Also, remove the old devel jenkins URL as we are now fully ready to use the one in the ITUP cluster.

### CODE REVIEW

**Comment by marmijo** [comment]
static code analysis was failing because single quotes were being used around strings containing GString expressions, so I added a commit to fix that. CI is failing now because the `STREAM` variable doesn't exist when validating the groovy syntax. Should we ignore that because `STREAM` would exist when running the pipeline?

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
> CI is failing now because the `STREAM` variable doesn't exist when validating the groovy syntax. Should we ignore that because `STREAM` would exist when running the pipeline?

I guess I don't fully understand. Is the CI that ran today on https://github.com/coreos/fedora-coreos-pipeline/pull/1038 not checking this same file? Shouldn't it have failed there too?

**Comment by jlebon** [comment]
It must be single quotes. Double quotes will do string interpolation at the Groovy level, which is not what we want. The `STREAM` variable is substituted by `substituteStr`.

You can waive the failing check in the Codacy panel. It doesn't understand what's going on it sounds like.

**Comment by marmijo** [comment]
> You can waive the failing check in the Codacy panel. It doesn't understand what's going on it sounds like.

Yeah, I figured there might be some sort of string substitution happening and that static code analysis thinks `${STREAM}` cant be evaluated properly.

> Is the CI that ran today on https://github.com/coreos/fedora-coreos-pipeline/pull/1038 not checking this same file?

Yes, it is! But, the file is changed in this PR causing the failure in CI.

**Pull request merged**
