### PR TITLE
build-podman-os: Fix secret name

### PR DESCRIPTION
**Pull request by ravanelli**

### CODE REVIEW

**Comment by ravanelli** [comment]
There were 2 secrets, forgot to the change the second one from mine.

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by jlebon** [comment]
Hmm, this one also seems like it should be changed:

> withCredentials([file(credentialsId: 'ravanelli-push-registry-secret', variable: 'REGISTRY_SECRET')]) {

**Comment by ravanelli** [comment]
> Hmm, this one also seems like it should be changed:
> 
> > withCredentials([file(credentialsId: 'ravanelli-push-registry-secret', variable: 'REGISTRY_SECRET')]) {

Fixed!

**Pull request merged**
