### PR TITLE
jobs/bump-jenkins-plugins: read plugins from 'main' branch

### PR DESCRIPTION
**Pull request by aaradhak**
To address the issue of local branch and origin/JenkinsPluginsUpdate getting diverged, we updated the Read Plugins.txt stage to read the `plugins.txt` from the `main` branch.

### CODE REVIEW

**Comment by aaradhak** [comment]
Posting the links of the test below:
Build - https://jenkins-fedora-coreos-pipeline.apps.ocp.stg.fedoraproject.org/job/bump-jenkins-plugins/200/console
PR opened- https://github.com/coreosbot-releng/fedora-coreos-pipeline/pull/19

**Comment by aaradhak** [comment]
@dustymabe @jlebon  can we set the head branches to be deleted automatically after the PR is merged in the `fedora-coreos-pipeline` of `coreosbot-releng` ?

**Comment by dustymabe** [comment]
I really don't understand why this is necessary. It should be fine to re-use the same branch name every time, right?

What problem does this solve?

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
