### PR TITLE
Add concept of a pipeline config (pipecfg) repo

### PR DESCRIPTION
**Pull request by dustymabe**
This is a tested version of https://github.com/coreos/fedora-coreos-pipeline/pull/619 minus the last commit which moves the pipeline config to a different repo. For now we keep the config in-repo while we iterate.

From the original PR:

This is a proposal for tackling the configuration issue laid out in https://github.com/coreos/fedora-coreos-pipeline/issues/618.

The high-level is:
- we convert `streams.groovy` to a YAML config file
- we move more knobs from the configmap to this YAML config file
- we support the YAML config file living in a separate repo

See the individual commits for details.

### CODE REVIEW

**Comment by dustymabe** [comment]
rebased on top of latest `main`

**Review by ravanelli — APPROVED** [review]
Thanks for adding all this Dusty

**Comment by travier** [comment]
I've rebased my branch on top of this one and it now fails with:

```
12:53:37  [Pipeline] load
12:53:37  [Pipeline] { (utils.groovy)
12:53:37  [Pipeline] }
12:53:37  [Pipeline] // load
12:53:37  [Pipeline] }
12:53:37  [Pipeline] // node
12:53:37  [Pipeline] End of Pipeline
12:53:37  java.lang.NoSuchMethodError: No such DSL method 'load_config' found among steps [_OcAction, _OcContextInit, _OcWatch, archive, bat, build, catchError, checkout, compareVersions, container, containerLog, deleteDir, dir, echo, envVarsForTool, error, fileExists, findFiles, getContext, git, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, mail, milestone, node, nodesByLabel, parallel, podTemplate, powershell, prependToFile, properties, publishChecks, publishHTML, pwd, pwsh, readCSV, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, resolveScm, retry, script, sh, sha1, sha256, slackSend, slackUploadFile, slackUserIdFromEmail, slackUserIdsFromCommitters, sleep, stage, stash, step, svn, tar, tee, timeout, timestamps, tm, tool, touch, unarchive, unstable, unstash, untar, unzip, validateDeclarativePipeline, verifySha1, verifySha256, waitUntil, warnError, withChecks, withContext, withCredentials, withEnv, withGroovy, wrap, writeCSV, writeFile, writeJSON, writeMavenPom, writeYaml, ws, zip] or symbols [GitUsernamePassword, all, allBranchesSame, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, aws, batchFile, bitbucket, bitbucketServer, booleanParam, branch, buildAllBranches, buildAnyBranches, buildButton, buildChangeRequests, buildDiscarder, buildDiscarders, buildNamedBranches, buildNoneBranches, buildRegularBranches, buildRetention, buildTags, buildingTag, builtInNode, caseInsensitive, caseSensitive, certificate, changeRequest, changelog, changeset, checkoutToSubdirectory, choice, choiceParam, clock, command, configFile, configFileProvider, configMapVolume, containerEnvVar, containerLivenessProbe, containerTemplate, credentials, cron, crumb, default, defaultFolderConfiguration, defaultView, demand, disableConcurrentBuilds, disableResume, dockerCert, dockerServer, dockerTool, downstream, dumb, durabilityHint, dynamicPVC, emptyDirVolume, emptyDirWorkspaceVolume, envVar, envVars, envVarsFilter, environment, equals, exact, expression, file, fileParam, filePath, fingerprint, fingerprints, frameOptions, freeStyle, freeStyleJob, fromDocker, fromScm, fromSource, git, gitBranchDiscovery, gitHubBranchDiscovery, gitHubBranchHeadAuthority, gitHubExcludeArchivedRepositories, gitHubExcludeForkedRepositories, gitHubExcludePublicRepositories, gitHubForkDiscovery, gitHubIgnoreDraftPullRequestFilter, gitHubPullRequestDiscovery, gitHubSshCheckout, gitHubTagDiscovery, gitHubTopicsFilter, gitHubTrustContributors, gitHubTrustEveryone, gitHubTrustNobody, gitHubTrustPermissions, gitTagDiscovery, gitUsernamePassword, github, githubAccessToken, githubProjectProperty, githubPush, globalConfigFiles, groovy, headRegexFilter, headWildcardFilter, hostPathVolume, hostPathWorkspaceVolume, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, isRestartedRun, issueCommentTrigger, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobBuildDiscarder, jobDsl, jobName, junitTestResultStorage, kubeconfig, kubernetes, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, mailer, masterBuild, maven, maven3Mojos, mavenErrors, mavenGlobalConfig, mavenMojos, mavenWarnings, merge, modernSCM, myView, namedBranchesDifferent, never, nfsVolume, nfsWorkspaceVolume, node, nodeProperties, nonInheriting, none, not, oc, onFailure, organizationFolder, override, overrideIndexTriggers, paneStatus, parallelsAlwaysFailFast, parameters, password, pattern, permanent, persistentVolumeClaim, persistentVolumeClaimWorkspaceVolume, pipeline, pipelineTriggers, plainText, plugin, podAnnotation, podEnvVar, podLabel, pollSCM, portMapping, preserveStashes, projectNamingStrategy, proxy, pruneTags, pullRequestReview, queueItemAuthenticator, quietPeriod, rateLimit, rateLimitBuilds, regex, resourceRoot, retainOnlyVariables, run, runParam, schedule, scmRetryCount, script, scriptApproval, scriptApprovalLink, search, secretEnvVar, secretVolume, security, shell, simpleBuildDiscarder, skipDefaultCheckout, skipStagesAfterUnstable, slackNotifier, slave, sourceRegexFilter, sourceWildcardFilter, sshPublicKey, sshUserPrivateKey, standard, status, string, stringParam, suppressAutomaticTriggering, swapSpace, tag, teamSlugFilter, text, textParam, timestamper, timestamperConfig, timezone, tmpSpace, toolLocation, triggeredBy, unsecured, untrusted, upstream, url, userSeed, usernameColonPassword, usernamePassword, viewsTabBar, weather, wildcards, withAnt, x509ClientCert, zip] or globals [buildImage, buildPod, checkoutToDir, cosaParallelCmds, cosaPod, currentBuild, env, fcosBuild, fcosKola, fcosKolaTestIso, gangplank, openshift, params, pipeline, pod, scm, shwrap, shwrapCapture, shwrapRc, utils, withPodmanRemote]
12:53:37  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:216)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
12:53:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:53:37  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:53:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:53:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:53:37  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
12:53:37  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
12:53:37  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
12:53:37  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
12:53:37  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
12:53:37  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
12:53:37  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
12:53:37  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
12:53:37  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
12:53:37  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
12:53:37  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:143)
12:53:37  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
12:53:37  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
12:53:37  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
12:53:37  	at WorkflowScript.run(WorkflowScript:15)
12:53:37  	at ___cps.transform___(Native Method)
12:53:37  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
12:53:37  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
12:53:37  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:78)
12:53:37  	at jdk.internal.reflect.GeneratedMethodAccessor219.invoke(Unknown Source)
12:53:37  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:53:37  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:53:37  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
12:53:37  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
12:53:37  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
12:53:37  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
12:53:37  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
12:53:37  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
12:53:37  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
12:53:37  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:403)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:97)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:315)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:279)
12:53:37  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
12:53:37  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:53:37  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
12:53:37  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
12:53:37  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
12:53:37  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
12:53:37  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:53:37  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:53:37  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:53:37  	at java.base/java.lang.Thread.run(Thread.java:829)
12:53:37  Finished: FAILURE
```

**Comment by dustymabe** [comment]
You probably need to delete and re-create your configuration as code configmap:

```
oc delete configmap/jenkins-casc-cfg
oc create configmap jenkins-casc-cfg --from-file=jenkins/config
```

and then re-spin your jenkins pod.

**Comment by travier** [comment]
Did that. Thanks. We should add that to the Hacking doc.

**Comment by dustymabe** [comment]
> Did that. Thanks. ~We should add that to the Hacking doc.~ I'm adding that to the HACKING guide.

It's in the hacking guide, but the hacking guide is geared towards initial deployment. You don't often need to change the casc configmap even when you are hacking.

Rule of thumb, if something isn't working just nuke and pave and if it still doesn't work then you've got a problem that needs to be investigated.

**Pull request merged**
