### PR TITLE
Jenkinsfile: add rerun flag

### PR DESCRIPTION
**Pull request by saqibali-2k**
Reruns have been disabled by default. Lets add the flag to turn
them on in the pipeline.

### CODE REVIEW

**Comment by dustymabe** [comment]
There are a few places in this repo where we call [`fcosKola()`](https://github.com/coreos/coreos-ci-lib/blob/main/vars/fcosKola.groovy) from `coreos-ci-lib`. I'm not sure whether we should update the lib or update our calls here to make sure `--rerun` gets added.

**Review by jlebon — APPROVED** [review]
LGTM! As @dustymabe mentioned, there is also `fcosKola`.

> I'm not sure whether we should update the lib or update our calls here to make sure `--rerun` gets added.

I think the behaviour makes sense as a default in all CI so I'd for updating the library. Ideally there's a way to opt-out though (`reruns: false`?).

**Comment by dustymabe** [comment]
ok yeah let's merge this and update the library. @saqibali-2k can you look into that?

**Comment by saqibali-2k** [comment]
> ok yeah let's merge this and update the library. @saqibali-2k can you look into that?

Can do!

**Pull request merged**
