### PR TITLE
Jenkinsfile: Add Vultr image build to pipeline

### PR DESCRIPTION
**Pull request by dghubble**
* Vultr images can't be uploaded yet, but it would be nice to build them in an automated fashion
* https://github.com/coreos/fedora-coreos-tracker/issues/355

### CODE REVIEW

**Comment by dghubble** [comment]
I've been building a new Vultr image every so often and checking them. It'd be nice to have the pipeline do the build and get it on https://builds.coreos.fedoraproject.org/browser

**Comment by dustymabe** [comment]
seems reasonable to me - we do this for other clouds which we can't upload to yet. @dghubble could you make a docs page for us like https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-azure/ ?

**Comment by dghubble** [comment]
Certainly https://github.com/coreos/fedora-coreos-docs/pull/71

**Comment by lucab** [comment]
Apparently we have a CI gap on this repo, as this PR broke the rest of coreos-ci:
```
+ cosa kola --upgrades
kola -p qemu-unpriv --output-dir tmp/kola-upgrade run-upgrade --qemu-image-dir tmp/kola-qemu-cache -v --find-parent-image
2020-05-11T06:27:15Z cli: Started logging at level INFO
2020-05-11T06:27:15Z cli: Started logging at level INFO
Error: failed to parse build: json: unknown field "vultr"
2020-05-11T06:27:16Z cli: failed to parse build: json: unknown field "vultr"
script returned exit code 2
```

**Comment by dghubble** [comment]
Oh no, thanks @lucab!

**Pull request merged**
