### PR TITLE
Jenkinsfiles: don't ignore errors from kola command

### PR DESCRIPTION
**Pull request by dustymabe**
If the kola command has trouble setting up for testing we should
make sure this get flagged up in the web UI.

### CODE REVIEW

**Comment by dustymabe** [comment]
cc @arithx - we probably did this for a reason.

**Comment by arithx** [comment]
The `kola` command also fails when any tests fail. Without the `|| :` we won't archive the test results (and/or the artifact) when tests fail.

**Comment by jlebon** [comment]
See prior discussions at https://github.com/coreos/fedora-coreos-pipeline/pull/114#discussion_r308408919.

**Comment by jlebon** [comment]
I filed https://github.com/coreos/mantle/issues/1059 to track this.

**Pull request closed without merging**
