### PR TITLE
HACKING.md: add note on running oc rootless

### PR DESCRIPTION
**Pull request by rfairley**
Add a note on running oc rootless while Docker by default requires
root, which tripped me up at first coming back to this.

### CODE REVIEW

**Comment by dustymabe** [comment]
adding the user to the docker group gives them root on the system so not sure if that's the best advice.

**Comment by jlebon** [comment]
Note you only need to run `oc cluster up` as root. Everything else can (and should) be done as non-root. Not super opposed to this, though yeah it's generally not recommended (see https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/).

Maybe let's just document that `oc cluster up/down` should be run as root?

**Comment by jlebon** [comment]
This is the bash alias I use BTW:

```bash
ocup() {
    local v=$1; shift
    local existing=

    if [ -z "$v" ]; then
        echo "Missing version!"
        return 1
    fi

    # just concentrate everything in /srv/oc to make it easier to wipe off
    local d=/srv/ocup/oc-$v
    if [ -d $d ]; then
        existing="--use-existing-config"
    else
        sudo mkdir -p $d/{config,data,pv}
    fi

    sudo oc cluster up \
        --host-config-dir=$d/config \
        --host-data-dir=$d/data \
        --host-pv-dir=$d/pv $existing \
        --version "$v" "$@"

    # transfer creds over from root dir so we can log in as system:admin
    if [ $UID -ne 0 ] && [ -n "$HOME" ]; then
        rm -rf $HOME/.kube
        sudo cp -r /root/.kube $HOME
        sudo chown -R $UID:$UID $HOME/.kube
    fi

    oc login -u developer
}
```

And then I do e.g. `ocup v3.6.1`,

Note the `sudo cp -r /root/.kube $HOME` as a consequence of standing up the cluster as root. (Also note this will wipe any other cached k8s creds).

**Comment by rfairley** [comment]
@dustymabe, @jlebon Agreed - makes sense to document running as root just for the commands that need it. Updated!

Thank you for linking the bash alias @jlebon, trying it on my system! (F30 Silverblue)

**Comment by rfairley** [comment]
Just did a minor last-minute push to adjust wording.

**Pull request merged**
