### PR TITLE
migrate credentials to kubernetes credentials plugin

### PR DESCRIPTION
**Pull request by dustymabe**
This patch set converts all credentials to be auto-created directly from kuberetes secrets. This means we don't have to mount the secrets into the jenkins or cosa pods and can bind them when needed at runtime using `withCredentials()`.

### CODE REVIEW

**Comment by dustymabe** [comment]
Probably best to review each commit individually. I can break some of this out into other PRs if desired as well.

I'll attempt to do some testing on this now in staging.

**Comment by dustymabe** [comment]
I've tested basic concepts here in staging:

- builds work
- archiving to s3 works
- multi-arch building works
- running an AWS kola test works

I'm ready to take this to production and flesh out any remaining issues or I'm open to input on how best to proceed.

**Comment by jlebon** [comment]
Awesome work!

A lot of non-trivial changes here. To make review easier, can we split it into a couple of smaller PRs? Even just in two would help. Otherwise, I'm OK keeping it all together but it'll take longer.

**Comment by dustymabe** [comment]
broke out the first 4 commits into https://github.com/coreos/fedora-coreos-pipeline/pull/648

**Comment by dustymabe** [comment]
another commit broken into https://github.com/coreos/fedora-coreos-pipeline/pull/650

**Comment by dustymabe** [comment]
and three more commits into https://github.com/coreos/fedora-coreos-pipeline/pull/651

**Comment by dustymabe** [comment]
one more commit broken out into https://github.com/coreos/fedora-coreos-pipeline/pull/653

**Comment by dustymabe** [comment]
two more commits broken out into https://github.com/coreos/fedora-coreos-pipeline/pull/656

**Comment by dustymabe** [comment]
All of this is now merged in other PRs.

**Pull request closed without merging**
