### PR TITLE
plugins.txt: freeze plugins to working versions

### PR DESCRIPTION
**Pull request by saqibali-2k**
We ran into a version mismatch between jenkins and the plugins
while setting up jenkins in the staging cluster. Lets freeze the
package versions to avoid the mismatch.

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
Hah, I meant only freezing the plugins that we need by looking at which ones exactly Jenkins is complaining about. But this works too for now!

**Comment by jlebon** [comment]
Did you verify that the latest Jenkins comes up successfully with this?

**Comment by dustymabe** [comment]
> Hah, I meant only freezing the plugins that we need by looking at which ones exactly Jenkins is complaining about. But this works too for now!

Yeah I told him to just freeze them all. Maybe we can work on https://github.com/coreos/fedora-coreos-pipeline/issues/562 soon?

**Comment by saqibali-2k** [comment]
> > Hah, I meant only freezing the plugins that we need by looking at which ones exactly Jenkins is complaining about. But this works too for now!
> 
> Yeah I told him to just freeze them all. Maybe we can work on #562 soon?

The issue was with  `configuration-as-code`, `ssh-credentials`, and `github`, but yep I just ended up freezing them all.

**Comment by saqibali-2k** [comment]
> Did you verify that the latest Jenkins comes up successfully with this?

⚠️ Currently running into some issues. Lets hold off for now ⚠️

**Comment by cgwalters** [comment]
Saqib is the Elsa of Jenkins plugins.

**Pull request merged**
