### PR TITLE
jenkins/plugins: update plugins to latest versions

### PR DESCRIPTION
**Pull request by marmijo**
Update all Jenkins plugins to their latest versions.

### CODE REVIEW

**Comment by dustymabe** [comment]
wow - some of those versions changed scheme completely.

**Review by dustymabe — APPROVED** [review]

**Comment by marmijo** [comment]
Yes, they were pretty out-of-date :smile:

**Comment by jlebon** [comment]
Did this work when you tested it? Looks like we needed https://github.com/coreos/fedora-coreos-pipeline/pull/930.

**Comment by marmijo** [comment]
Ah, thanks for catching that! I wasn't able to test it at the time as this PR was in response to Jenkins failing to come up with outdated plugins.

**Pull request merged**
