### PR TITLE
release: Add `time -v` as part of fetch cmd for debugging

### PR DESCRIPTION
**Pull request by ravanelli**
- We are having trouble detecting why fetch is failing from time to time. To track it a little better, let's add it for a while.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
Thanks!

**Comment by dustymabe** [comment]
do all the older RHCOS branches have `time` in COSA?

**Comment by jlebon** [comment]
> do all the older RHCOS branches have `time` in COSA?

Good catch. Looking at older branches, it doesn't seem like it. Let's temporarily revert this for now so it doesn't break the release job on older RHCOS: https://github.com/coreos/fedora-coreos-pipeline/pull/791.

**Comment by jlebon** [comment]
This is re-added in https://github.com/coreos/fedora-coreos-pipeline/pull/837 now that it's in all cosa branches.

**Pull request merged**
