### PR TITLE
Jenkinsfiles: add hint for vim to choose correct sytax highlighting

### PR DESCRIPTION
**Pull request by dustymabe**
Without the .groovy extension these files won't get any highlighting.
Setting this on the modeline helps.

### CODE REVIEW

**Comment by jlebon** [comment]
Not against, though with this you'll get even better highlighting: https://github.com/martinda/Jenkinsfile-vim-syntax. :)

**Comment by dustymabe** [comment]
> Not against, though with this you'll get even better highlighting: https://github.com/martinda/Jenkinsfile-vim-syntax. :)

seems like this `Simply recognises your project's Jenkinsfile as a Groovy script.` So it's effectively the same as what I'm doing here, except the change in this PR will work for anyone who hasn't specifically installed that plugin? It would be nice if we could get that plugin in Fedora.

**Comment by jlebon** [comment]
Hmm, I think that comment might be outdated. It definitely highlights Jenkins-specific things: https://github.com/martinda/Jenkinsfile-vim-syntax/blob/master/syntax/Jenkinsfile.vim.

**Comment by jlebon** [comment]
And the problem is that with those hints, I actually get worse highlighting because it's using the Groovy syntax highlighter. :(

**Pull request closed without merging**
