### PR TITLE
pipeline: start creating ibmcloud artifacts

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Review by jlebon — APPROVED** [review]

**Review by darkmuggle — APPROVED** [review]
LGTM

**Comment by dustymabe** [comment]
Thanks. Will merge this once a new COSA has been built with https://github.com/coreos/coreos-assembler/pull/1740

**Comment by dustymabe** [comment]
OK, I reworked this a bit too because I noticed AWS was missing when I was updating the CI job in the COSA PR. So now I made them be in alphabetical order and I also added AWS to the list.

**Review by darkmuggle — APPROVED** [review]
LGTM

**Review by jlebon — APPROVED** [review]
Nice!

**Pull request merged**
