### PR TITLE
WIP: RHCOS pipeline changes

### PR DESCRIPTION
**Pull request by ravanelli**
This PR contains a rebase with main and `rhcos` branch

### CODE REVIEW

**Comment by jlebon** [comment]
With the first commit in https://github.com/coreos/fedora-coreos-pipeline/pull/666, you should be able to just add `yumrepos` to the config YAML and drop [b0e4350](https://github.com/coreos/fedora-coreos-pipeline/pull/652/commits/b0e43508644f4e0540afbb00def17b68ad063a39).

**Comment by jlebon** [comment]
When rebasing onto https://github.com/coreos/fedora-coreos-pipeline/pull/671, you'll want to rerun `jenkins.yaml` using something like this:

```
oc process --filename=manifests/jenkins.yaml --param=NAMESPACE=... ... | oc replace -f -
```

And then rerun `./deploy` as well and start another build of `jenkins-agent`.

**Comment by cgwalters** [comment]
For testing purposes we can make `quay.io/rhel-coreos-devel` or whatever right?  I imagine we could also ask DPTP to run a quay instance in the CI cluster...

**Comment by jlebon** [comment]
> For testing purposes we can make `quay.io/rhel-coreos-devel` or whatever right? I imagine we could also ask DPTP to run a quay instance in the CI cluster...

Right, we could do that. I'd prefer pushing to a namespace that already exists though so we don't have to manage yet another account somewhere and track its credentials, etc... If that doesn't exist, creating one sounds fine.

**Comment by cgwalters** [comment]
Related to this though, I have some more work in the background for https://github.com/coreos/coreos-assembler/issues/2685 which as you know turns this all on its head - the *canonical source of truth* is a container image, so in this model a registry is required, s3 is optional.

**Pull request closed without merging**
